### ISSUE TITLE
Unhandled Bad Request when try to register new user

### ISSUE THREAD

**Issue by IT-agencyAtom** [DavidAJohn/BookwormsLendingLibrary#26]
When try to register new user with week password ("123456") - answer is Bad Request.

![image](https://github.com/user-attachments/assets/54d922c9-f315-4247-b090-af1128525fc9)

**Comment by IT-agencyAtom** [comment]
I already fix this bug, how I can add pullrequest with fix? I take your code (thx for it xD), and want to improve it for using in real production.

**Comment by DavidAJohn** [comment]
Thanks for your interest in the project and for identifying this bug. I appreciate you taking the time to do it.

However, I would **not** recommend using this project as the basis for a production application. It was not created with production use in mind. I've clarified this in the ReadMe file.

As you've already noticed, the authentication system is a very basic implementation of ASP.Net Identity, and there are also problems with the way I've written it. Realistically it would need to be completely replaced with a more robust solution like Identity Server or Active Directory in a production application.

While I don't have any plans to incorporate those kinds of extensive changes into my version of the project (so I'm not really  looking to accept PRs), I wish you good luck if that's what you intend to do with your fork.

If you haven't already, I'd also recommend looking at the different options that are available with Blazor as of .NET 8. This type of Blazor Server project structure is now considered a little out of date.

Thanks again,

David

**Comment by IT-agencyAtom** [comment]
> Thanks for your interest in the project and for identifying this bug. I appreciate you taking the time to do it.
> 
> However, I would **not** recommend using this project as the basis for a production application. It was not created with production use in mind. I've clarified this in the ReadMe file.
> 
> As you've already noticed, the authentication system is a very basic implementation of ASP.Net Identity, and there are also problems with the way I've written it. Realistically it would need to be completely replaced with a more robust solution like Identity Server or Active Directory in a production application.
> 
> While I don't have any plans to incorporate those kinds of extensive changes into my version of the project (so I'm not really looking to accept PRs), I wish you good luck if that's what you intend to do with your fork.
> 
> If you haven't already, I'd also recommend looking at the different options that are available with Blazor as of .NET 8. This type of Blazor Server project structure is now considered a little out of date.
> 
> Thanks again,
> 
> David

Understand 😊 
Ok, will continue with fork 😁 
Thanks for your work ☺️
